### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by AlexMubarakshin**
Formating code
Clear input after sending message
Correct spell

### CODE REVIEW

**Comment by AlexMubarakshin** [comment]
Hello. I liked your project. I've made a few changes.
I will be glad to contribute to your project. 😉

**Comment by XboxYan** [comment]
@AlexMubarakshin 
Thank you ❤.
However, this is a personal project, which is still under development, and many functions are not yet completed.
Also, the Chinese Spring Festival( 2.4~2.10 ) is coming soon, and it may be impossible to invest in it for some time.🎉

**Comment by AlexMubarakshin** [comment]
Ok, got it. I will follow the progress of the project. ❤️

**Comment by AlexMubarakshin** [comment]
Ok, got it. I will follow the progress of the project. ❤️

**Pull request closed without merging**
